services:
  backend:
    build: ./legisloop-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      NEWSAPI_API_KEY: ${NEWSAPI_API_KEY}
      LEGISCAN_API_KEY: ${LEGISCAN_API_KEY}
      LEGISLOOP_API_KEY: ${LEGISLOOP_API_KEY}
    depends_on:
      - frontend
    networks:
      - web

  frontend:
    build: ./legisloop-frontend
    ports:
      - "3000:80"

    networks:
      - web

networks:
  web:
