version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: legisloop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - legisloop_network

networks:
  legisloop_network:


volumes:
  postgres_data:
    driver: local
