name: Test Backend Build

on:
  pull_request:
    branches:
      - main
      - skeleton

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven 

      - name: Check Compile
        working-directory: legisloop-backend
        run: | 
            mvn clean install
            mvn compile
            