name: Build and Publish Dockerfile

on:
  push:
    branches:
      - main
      - skeleton
  workflow_dispatch: # Allows for manual triggering

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Backend Image 
        uses: docker/build-push-action@v4
        with: 
            push: true
            context: ./legisloop-backend
            tags: |
                ghcr.io/aleef02/legisloop/legisloop-backend:${{ github.sha }}
                ghcr.io/aleef02/legisloop/legisloop-backend:latest

      - name: Build and Frontend Image 
        uses: docker/build-push-action@v4
        with: 
            push: true
            context: ./legisloop-frontend
            tags: |
                ghcr.io/aleef02/legisloop/legisloop-frontend:${{ github.sha }}
                ghcr.io/aleef02/legisloop/legisloop-frontend:latest
